name: GitHub pages

on:
  push:
    branches: [main]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'index.md'
          destination_repo: 'Istchanar/git-basics-pages'
          destination_branch: 'git-basics'
          user_name: ${{ github.actor }}