name: GitHub pages

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and check
        run: |
          npm install
          npm run prettier:check-all

  github-pages:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "index.md"
          destination_repo: "Istchanar/git-basics-pages"
          destination_branch: "git-basics"
          user_name: ${{ github.actor }}
